### ISSUE TITLE
Updates: Newer MSU Version from Lenovo and auto wget utility

### ISSUE THREAD

**Issue by fermulator** [stegm/marvell_msu_docker#1]
Hi!

Impressive work here!  I stumbled over this repo and gave it a whirl, it achieves _quite_ the excellent accomplishment for Marvell RAID MSU.

I made a few improvements/fixes/updates in my fork: https://github.com/fermulator/marvell_msu_docker
(feel free to pull in if you want ;o)

**Comment by stegm** [comment]
Hi!

Fantastic! I soon as I have a little time left, I will merge in you PR and give it a try on my server.

Thank you for sharing your changes!

**Comment by stegm** [comment]
I merged your PR with some slightly changes:
* I use a multistage build to avoid installing packages in the final image which aren't needed afterwards (unzip/wget)
* I comment out the COPY because the build fails if no local file exists (I also change the documentation to this).

Thank you very much for the update.
